// Generated by https://quicktype.io

export interface CookBookModel {
  status: string;
  info: string;
  cookbooks: Cookbook[];
}

export interface Cookbook {
  id: string;
  parent: string;
  description: string;
}
